POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bageme",
  "email": "bage@test.com",
  "role": "admin"
}

###

GET http://localhost:3000/users

###
POST http://localhost:3000/plan/plan
Content-Type: application/json


{
  "user_id": 1,
  "start_date": "2025-01-01",
  "end_date": "2025-12-31",
  "amount_per_month": 50000
}

###
GET http://localhost:3000/plan/plan