POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bageme",
  "email": "bage@test.com",
  "role": "admin"
}

###

GET http://localhost:3000/users

###
POST http://localhost:3000/plan/plan
Content-Type: application/json


{
  "user_id": 1,
  "start_date": "2025-01-01",
  "end_date": "2025-12-31",
  "amount_per_month": 50000
}

###
GET http://localhost:3000/plan

###
POST http://localhost:3000/contribution
Content-Type: application/json

{
  "user_id": 1,
  "required_amount": 1000.00,
  "month": "january"
}

###
GET http://localhost:3000/contribution


###
POST http://localhost:3000/payment
Content-Type: application/json

{
  "user_id": 1,
  "contribution_id": 1,
  "amount": 50.00,
  "date": "2025-01-05",
  "method": "cash",
  "reference": "RCPT-001"
}

###
GET http://localhost:3000/payment
